Add FAQ page
jonogon/jonogon-mono pull request #101
Opened 2024-09-10 16:12 UTC by errhythm

The current FAQ button redirects user to Notion which might disrupt their experience. Created FAQ page with markdown support to allow markdown formatting in question answers of the FAQ.

2024-09-13 17:02 UTC, riya09 requested changes

2024-09-13 17:02 UTC, riya09 commented on apps/jonogon-web-next/src/app/faq/page.tsx
> +            <CollapsibleContent>
maybe we can keep the design like this, both question and answer in one box, what do you think?

<img width="631" alt="Screenshot 2024-09-13 at 11 01 06 PM" src="https://github.com/user-attachments/assets/ff5351d2-8a99-4b85-9fe2-137eaf6a5a8b">

2024-09-13 17:06 UTC, riya09 commented on apps/jonogon-web-next/src/app/contributors/page.tsx
>  								target="_blank"
I think this page don't have to open in new tab anymore

2024-09-13 20:01 UTC, errhythm commented on apps/jonogon-web-next/src/app/faq/page.tsx
> +            <CollapsibleContent>
Sure. It looks great. Thanks for reviewing as well. I still have a lot to learn.

2024-09-14 07:11 UTC, riya09 requested changes

2024-09-14 07:11 UTC, riya09 commented on apps/jonogon-web-next/src/app/faq/page.tsx
> +  const [openItems, setOpenItems] = useState<number[]>([]);
you don't need this anymore i guess

2024-09-14 07:11 UTC, riya09 commented on apps/jonogon-web-next/src/app/faq/page.tsx
> +              {openItems[index] ?
```suggestion
              {openItems[index] ? (
```

2024-09-14 07:11 UTC, riya09 commented on apps/jonogon-web-next/src/app/faq/page.tsx
> +  };
remove this section
```suggestion
    
```

2024-09-14 08:43 UTC, riya09 commented on apps/jonogon-web-next/src/app/faq/page.tsx
> +  const [openItems, setOpenItems] = useState<number[]>([]);
> you don't need this anymore i guess

make changes in your code, commit it and push it here.

2024-09-14 08:59 UTC, errhythm commented on apps/jonogon-web-next/src/app/faq/page.tsx
> +  const [openItems, setOpenItems] = useState<number[]>([]);
Updated. Please check.

2024-09-14 12:15 UTC, riya09 submitted a review, later dismissed
Looks good 👍🏼 . Great work.

Just a small suggestion. The notion page also have other content like community guidelines, manifesto and press. So, better to add a question in faq and link the notion to the answer.

The question can be something like this-

What are the community guidelines and manifesto?

To know more about the community guidelines, manifesto and press releases [click here](https://elvista.notion.site/Jonogon-962f56d9d6ea42d3839790c2146b7f6a)

2024-09-14 15:19 UTC, errhythm commented
Thanks a lot for the suggestions. I have added the FAQ question. Also added `prose` class in question and answer to properly format the text so no need to include components explicitly. 

![image](https://github.com/user-attachments/assets/90197fc0-4339-4abe-aa4d-9d45a25533c0)

2025-10-08 18:19 UTC, closed without merging