Add Similar Petitions Suggestion while creating a petition
jonogon/jonogon-mono pull request #123
Opened 2024-10-05 11:57 UTC by errhythm

Added a Similar Petitions card, which will prompt the user if their petition already exists. Used the Stopword package to remove the stopwords from the title, which would increase the accuracy of the search. 

![image](https://github.com/user-attachments/assets/941f178f-50b0-4df8-a98c-9ed328c514f3)

https://github.com/user-attachments/assets/1a054b1d-ebea-46a3-ae96-fefbe157eb4f

Please review and suggest any necessary changes; I am still a newbie. Also, I found that the suggestion result could be increased with Postgres [pg_trgm](https://www.postgresql.org/docs/current/pgtrgm.html), but I need to familiarize myself with it.

2024-10-06 12:25 UTC, errhythm commented
Updated the search accuracy and changed the card UI. 

![image](https://github.com/user-attachments/assets/b3678663-8190-412b-b165-81add7e5a5f6)

2024-10-08 18:33 UTC, getanwar requested changes
Please check my comments :)

2024-10-08 20:10 UTC, errhythm commented on apps/jonogon-core/src/api/trpc/procedures/petitions/listing/list-petitions.mts
> +                        petition.title!.toLowerCase().includes(keyword.toLowerCase())
My bad. You are right. I meant to use (`?.`) instead.

2024-10-08 20:11 UTC, errhythm commented on apps/jonogon-web-next/src/components/custom/SimilarPetitionsSuggestions.tsx
> +import { debounce } from 'lodash';
Got it. I will fix it as well. Thank you.

2024-10-08 21:02 UTC, errhythm commented
> Please check my comments :)

Thanks. I have fixed it according to your suggestions.

2024-10-09 07:19 UTC, getanwar approved these changes

2024-10-17 17:28 UTC, merged