Add modal with guidelines to Submit দাবি
jonogon/jonogon-mono pull request #132
Opened 2024-10-22 08:43 UTC by errhythm

To ensure that everyone who is posting knows what can be posted and so that they accept the rules & regulations. 

https://github.com/user-attachments/assets/cc94e547-adb3-42d3-aa93-a9a6f7e45106

![image](https://github.com/user-attachments/assets/2418ca1b-3030-4292-9cc5-45d0200f4cbf)

2024-10-22 18:01 UTC, fluentmoheshwar approved these changes

2024-10-25 14:12 UTC, riya09 requested changes

2024-10-25 14:12 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +    return (
better to control open and close from here
```
 const [isOpen, setIsOpen] = useState(false)
    useEffect(() => {
        setIsOpen(true)
    }, [])
    const onClose = () => {
        setIsOpen(false);
        // emit this in parent component and handle accordingly
        onNavigate()
    }
    const onAccept = () => {
        setIsOpen(false);
    }
```

2024-10-25 14:12 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +        <Dialog open={isOpen} onOpenChange={onClose}>
there are some issues with the styling, in mobile view the content is overflowed
<img width="373" alt="Screenshot 2024-10-25 at 8 01 28 PM" src="https://github.com/user-attachments/assets/8135206c-3732-498b-8f00-36d7ded0f909">

2024-10-25 14:12 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +            <DialogContent
also in devices where height is smaller, the content disappears from top


https://github.com/user-attachments/assets/e945cff3-fb59-41a7-a7c7-6b000a0350e3

2024-10-25 14:52 UTC, errhythm commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +        </Dialog>
Got it. I think your suggestion solved the mobile view styling issue, and content disappearance from the top when the height is smaller. Thanks, now it seems better.

2024-10-25 15:19 UTC, errhythm commented on apps/jonogon-web-next/src/app/petition/draft/_page.tsx
> +    const [isModalOpen, setIsModalOpen] = useState(true);
Got it, I created a new prop `shouldShow ` to handle the navigation and used `useState` and `useEffect` directly in the component. Please check it if its correct.

2024-10-25 16:28 UTC, riya09 requested changes

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +                            onClick={onAccept}
accept button not working, your function name is `handleAccept`

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/app/petition/draft/_page.tsx
> +    const [isModalOpen, setIsModalOpen] = useState(true);
you won't be needing this state in this component, you have already handled open/close in main component

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/app/petition/draft/_page.tsx
> +                }}
this can be simplified
```
<RegulationsModal onClose={() => router.push('/')} />
```

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/app/petitions/[id]/edit/page.tsx
> +    const [isModalOpen, setIsModalOpen] = useState(!!params.get('fresh'));
similarly you won't have to declare state here

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/app/petitions/[id]/edit/page.tsx
> +            <RegulationsModal
this can be simplified too
```
<RegulationsModal
     shouldShow={!!freshValue}
     onClose={() => {
       if (freshValue) {
          router.push('/');
        }
     }}
 />
```

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +    onAccept: () => void;
you can make both of these props optional, so that you don't have to declare them if not needed
```
    onClose?: () => void;
    onAccept?: () => void;
```

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +        onClose();
handle undefined
```
onClose?.()
```

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +    shouldShow = false,
default should be `true`

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +        onAccept();
handle defined here too `onAccept?.()`

2024-10-25 16:28 UTC, riya09 commented on apps/jonogon-web-next/src/components/custom/RegulationsModal.tsx
> +        <Dialog open={isOpen} onOpenChange={onClose}>
function name needs to be updated
`onOpenChange={handleClose}`

2024-10-25 17:07 UTC, errhythm commented
I've fixed them. My bad. I forgot to change the variable after merging the suggested code. (Still learning 😓😅)

2024-10-25 17:19 UTC, riya09 approved these changes
Thanks for going through all the reviews.Great work 👍🏼

2024-10-25 20:33 UTC, merged