[WIP] feat: flag dabi
jonogon/jonogon-mono pull request #134
Opened 2024-10-28 16:00 UTC by 0xriyadh

### The Problem:
There are instances where a moderator mistakenly approves a দাবি that DOESN’T follow the community guidelines. During those cases - these দাবিs might pick up traction and we need to “elegantly” flag these dabis so that they don’t show on the feed. 

### The Solution:
The ability to flag a দাবি by moderators - from the দাবি details page. 

Once a  দাবি is flagged the following will happen : 

- [ ] It gets removed from the main feeds.
- [ ] It gets stored in another filter in the dropdown as “Flagged”
- [ ] These দাবিs cannot be voted on anymore BUT they can be commented on
- [ ] Moderators must also have the option to “Unflag” a দাবি

2024-10-29 08:38 UTC, riya09 reviewed
Just a small suggestion, better not to make push with same commits.Becomes really difficult to keep track of the changes over time. I see you have written description, but better to move the description as title. The description is for when your title over limits the title character

2024-10-29 08:42 UTC, 0xriyadh commented
> Just a small suggestion, better not to make push with same commits.Becomes really difficult to keep track of the changes over time. I see you have written description, but better to move the description as title. The description is for when your title over limits the character

Will keep that in mind, thank you for the suggestion.

2024-10-29 09:35 UTC, 0xriyadh commented
@riya09 @omranjamal the PR is ready for review.

2024-10-29 17:11 UTC, riya09 requested changes

2024-10-29 17:11 UTC, riya09 commented on apps/jonogon-web-next/src/app/page.tsx
> +                            <SortOption sort={'flag'}>Flagged</SortOption>
<img width="189" alt="Screenshot 2024-10-29 at 11 08 07 PM" src="https://github.com/user-attachments/assets/9a159cfa-e024-48ec-aee1-0d4a2507821b">

can we try something like this?

2024-10-29 17:11 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/petitions/listing/list-petitions.mts
> +            sort: z.enum(['time', 'votes', 'flag']).default('votes'),
logically it actually does not make sense to keep `flag` in sort. It is actually not any order right? Also you have to repeat the same query for formalized and all dabis, which is also repetitive

Better to keep it in `filter`

2024-10-30 00:21 UTC, 0xriyadh commented on apps/jonogon-web-next/src/app/page.tsx
> +                            <SortOption sort={'flag'}>Flagged</SortOption>
This is way better, imo

2024-10-30 04:32 UTC, riya09 requested changes

2024-10-30 04:32 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/petitions/listing/list-petitions.mts
> +            sort: z.enum(['time', 'votes', 'flag']).default('votes'),
@0xriyadh, move this to filter on top
```
filter: z.enum(['request', 'formalized', 'own', 'flag'])
```

2024-10-30 04:32 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/petitions/listing/list-petitions.mts
> +                                if (input.sort === 'flag') {
since we are considering flag as filter, we won't be checking like this with sort.
Need to check like `request` and `formalized`
```
.let((query) => {
  ....
  else if (input.filter === 'flag') {
    .where(
      'petitions.approved_at',
      'is not',
      null,
    )
    .where(
      'petitions.flagged_at',
      'is not',
      null,
    );
  }
}
```

2024-10-30 04:39 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/petitions/listing/list-petitions.mts
> +            sort: z.enum(['time', 'votes', 'flag']).default('votes'),
`flagged` would make sense more

2024-10-30 10:25 UTC, 0xriyadh commented on apps/jonogon-core/src/api/trpc/procedures/petitions/listing/list-petitions.mts
> +                                if (input.sort === 'flag') {
@riya09 done

2024-10-30 10:25 UTC, 0xriyadh commented
@riya09 addressed the issues you have raised. Kindly check now.

2024-10-30 17:00 UTC, riya09 approved these changes
Nicely done 👍🏼

2024-10-30 17:02 UTC, riya09 approved these changes
Just a heads up, if you are using vscode maybe the file gets auto format, as a result unchanged logic also come in the commit. Better do a check before committing or change the formatting setting in vscode

2024-10-30 17:03 UTC, merged