Update the Social Share OpenGraph Image with দাবির stats
jonogon/jonogon-mono pull request #136
Opened 2024-11-03 14:41 UTC by errhythm

- [x] Added new TRPC procedure for fetching petition OG image details
- [x] Completed the Opengraph Image Template
- [ ] Add a custom layout so that it doesn't show the Navigation bar
- [ ] Optimized the page so that there's as little JS as possible for the image preview page

2024-11-03 18:21 UTC, riya09 requested changes

2024-11-04 05:32 UTC, riya09 requested changes

2024-11-04 05:32 UTC, riya09 commented on apps/jonogon-web-next/src/app/petition/(opengraph-image)/preview-image/[id]/page.tsx
> +                    <img
probably need a fallback image for profile pic in case where there is no profile image available

2024-11-04 14:30 UTC, errhythm commented
Ok, I am trying that now.

2024-11-04 19:11 UTC, errhythm commented on apps/jonogon-web-next/src/app/petition/(opengraph-image)/preview-image/[id]/page.tsx
> +                    <img
Added.

2024-11-05 07:37 UTC, merged