Integration of frontend logic for flagging dabi
jonogon/jonogon-mono pull request #140
Opened 2024-11-07 09:34 UTC by 0xriyadh

This pr is to complete the frontend work for the `Flag Dabi` feature being added to the product.

2024-11-07 15:47 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                    Your petition was flagged.
For logged out user,the text isn't right I guess.
It can be `This petition was flagged`

2024-11-07 15:49 UTC, riya09 requested changes

2024-11-07 15:49 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                    Your petition was flagged.
I am not seeing any message when I am logged out.
For both logged in and logged out user I think we need the message
Also, we need to use a general message here
`This petition was flagged`

2024-11-07 15:50 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                    Your petition was flagged.
maybe we can make a separate block to control this

2024-11-07 15:56 UTC, riya09 requested changes

2024-11-07 15:56 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                status === 'flagged' ? (
rather than approving it, can we unflag it by setting flagged_at null. I think approving it changing the time when the time when the post was first seen was feed, which shouldn't be the case.Also, for the feed algorithm we are using this, so this might affect the score.

probably need to add flagged_at key in api, which can be optional?

2024-11-07 18:47 UTC, 0xriyadh commented on apps/jonogon-web-next/src/app/(interactive)/page.tsx
> +    const updateParams = () => {
aaa, because `own` is also a filter, when I click on `Flagged দাবিs` the filter gets replaced. I am thinking of solving this in either of these two approaches:

**Approach 1**
1. discard `own` from filter
2. add another parameter in the query called `ownPetitions` or something consisting a boolean value. Which will indicate if I am sorting and filtering my own petitions or all petitions.

**Approach 2**
1. discard `own` from filter
2. Move own petition page to a separate route like `/own-petitions`

2024-11-07 19:08 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/page.tsx
> +    const updateParams = () => {
I think it's better to move to new route. Approach 2 is better I guess. But discarding `own` you meant, from frontend right?

2024-11-07 19:21 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/page.tsx
> +    const updateParams = () => {
I would say if it's too much changes, let's do it after release. What do you think?

2024-11-07 19:30 UTC, 0xriyadh commented on apps/jonogon-web-next/src/app/(interactive)/page.tsx
> +    const updateParams = () => {
> I think it's better to move to new route. Approach 2 is better I guess. But discarding `own` you meant, from frontend right?

Yes, from frontend. 

> I would say if it's too much changes, let's do it after release. What do you think?

After release you mean, after merging this branch to main? I have no issues with either of them. But if we want to fully complete the feature before merging I think we can get it done within next 1/2 days.

2024-11-07 19:31 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/page.tsx
> +    const updateParams = () => {
ok then let's do the full 🚀

2024-11-07 19:34 UTC, 0xriyadh commented on apps/jonogon-web-next/src/app/(interactive)/page.tsx
> +    const updateParams = () => {
Also I think we need to fix some logic in the backend as well. Like when we will query for 'own' and 'flagged'. Same issue will arise.

2024-11-09 00:56 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/page.tsx
> +    const updateParams = () => {
If we need to change the full api flow in backend, then I think it's better to skip this for now. In my-petitions page, we can hide the Flag filter from dropdown for now.

2024-11-09 01:33 UTC, 0xriyadh commented on apps/jonogon-web-next/src/app/(interactive)/page.tsx
> +    const updateParams = () => {
> If we need to change the full api flow in backend, then I think it's better to skip this for now, as a lot of thing is connected. In my-petitions page, we can hide the Flag filter from dropdown for now.

that's true, ok let's do it separately

2024-11-09 01:54 UTC, 0xriyadh commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                status === 'flagged' ? (
yes, it seems like the better approach

2024-11-09 03:48 UTC, 0xriyadh commented
@riya09 done with all the discussed changes

2024-11-09 08:40 UTC, riya09 reviewed
One last thing, we also need to turn off commenting for flagged dabi. Let's hide comment box for flagged dabi

2024-11-09 10:01 UTC, riya09 requested changes

2024-11-09 10:01 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +            await utils.petitions.get.invalidate({id: petition_id});
if we add the `flagged` key in payload, we can use `isFlagged` variable here
```
{id: petition_id, flagged: !isFlagged }

2024-11-09 15:17 UTC, 0xriyadh commented
> One last thing, we also need to turn off commenting for flagged dabi. Let's hide comment box for flagged dabi

But I think Naseef bhai wanted to keep the comment section open?

2024-11-09 15:23 UTC, riya09 commented
> > One last thing, we also need to turn off commenting for flagged dabi. Let's hide comment box for flagged dabi
> 
> But I think Naseef bhai wanted to keep the comment section open?
> 
> ![image](https://private-user-images.githubusercontent.com/77486566/384619920-1f25f203-acb1-4f36-ba8c-99bdd1da43ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjYwMjIsIm5iZiI6MTczMTE2NTcyMiwicGF0aCI6Ii83NzQ4NjU2Ni8zODQ2MTk5MjAtMWYyNWYyMDMtYWNiMS00ZjM2LWJhOGMtOTliZGQxZGE0M2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDE1MjIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NDEwNWQ0OWQ4MzBiNDQ4OWM2NGI0MTE4OGM1YzAxZmI3OTYxYmY0YjU4ODg5YTc4Mjk2ODA3Y2I2M2Q2ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fyPQUfB28AdRY2KR6E8SZ3_8Q1ReELJ_1p9bkVJ6Wco)

Oh sorry, I haven’t seen that. Thanks for pointing it out.Ok then let’s keep it as it is.

2024-11-09 16:16 UTC, 0xriyadh commented
@riya09 all done apu

2024-11-09 16:37 UTC, riya09 requested changes

2024-11-09 16:37 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                                flagged: true,
I think you are doing the opposite. `flagged` true should mean the post is sent to flagged list. In the api you should also update. I find it kind of confusing when I read it.
What do you think?

2024-11-09 16:39 UTC, riya09 requested changes

2024-11-09 16:39 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                                    flagged: false,
when you are flagging it, shouldn't it be true?

2024-11-09 16:39 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/petitions/moderation.mts
> +                flagged_at: input.flagged ? null : new Date(), // Set the current timestamp
i think the opposite will make it more readable

2024-11-09 16:43 UTC, 0xriyadh commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                                    flagged: false,
Umm, my thought was with the variable `flagged` we are indicating if the petition is already flagged or not. If `flagged` is true, means the petition is already flagged and we should `unflag` and vice versa. But if we wanted to do the opposite shouldn't we use a parameter called `flag` instead of `flagged`? The `flag` variable would indicate if we should flag or not. However, I kind of like the current implemented approach. Am I missing something?

2024-11-09 16:48 UTC, riya09 commented on apps/jonogon-web-next/src/app/(interactive)/petitions/[id]/_page.tsx
> +                                                    flagged: false,
Ok, I understood your thought process. I didn't initially suggest `flag` since it would become same as api name :P so suggested `flagged` on that sense. Anyway, this is also fine. Good to go 👍🏼

2024-11-09 16:49 UTC, riya09 approved these changes

2024-11-09 16:51 UTC, merged