[WIP] Jobab api endpoints
jonogon/jonogon-mono pull request #147
Opened 2024-12-20 06:47 UTC by 0xriyadh

2024-12-20 17:30 UTC, riya09 requested changes

2024-12-20 17:30 UTC, riya09 commented on apps/jonogon-core/src/api/http/handlers/jobabs/attachment.mts
> +
since these two conditions need to be check in number of APIs, let's make a separate file in `utility` folder-
```js
// auth-utils

import { Response } from 'express';

interface AuthContext {
  auth?: {
      user_id?: string;
      is_user_moderator?: boolean;
      is_user_admin?: boolean;
  };
}

export function requireAuth(ctx: AuthContext, res: Response, message: string): boolean {
  if (!ctx.auth?.user_id) {
      res.status(401).json({ message });
      return false;
  }
  return true;
}

export function requireModeratorOrAdmin(ctx: AuthContext, res: Response, message: string): boolean {
  if (!ctx.auth.is_user_moderator && !ctx.auth.is_user_admin) {
      res.status(403).json({ message });
      return false;
  }
  return true;
}
```
you can then call this with customized message
```
requireAuth(ctx, res, 'must be logged in to upload attachments');

requireModeratorOrAdmin(ctx, res, 'only moderators can add attachments to jobabs');
```

2024-12-20 17:30 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/crud.mts
> +            .where('id', '=', `${input.id}`)
where('id', '=', input.id)

2024-12-20 17:30 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/crud.mts
> +
add a check if petition exist first
```js
const petition = await trx
                .selectFrom('petitions')
                .select(['id', 'created_by'])
                .where('id', '=', input.petition_id)
                .where('deleted_at', 'is', null)
                .executeTakeFirst();

            if (!petition) {
                throw new TRPCError({
                    code: 'NOT_FOUND',
                    message: 'Petition not found',
                });
            }
```

2024-12-22 03:01 UTC, 0xriyadh commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/crud.mts
> +            .where('id', '=', `${input.id}`)
Get this TS error
<img width="697" alt="image" src="https://github.com/user-attachments/assets/c483aca9-e095-4429-b668-088d99b7fd9d" />

2024-12-22 03:03 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/crud.mts
> +            .where('id', '=', `${input.id}`)
Ah! Ignore this review then

2024-12-23 12:17 UTC, riya09 reviewed
For now looks good, do you want to add the comment APIs in this PR too?

2024-12-24 06:22 UTC, 0xriyadh commented
> For now looks good, do you want to add the comment APIs in this PR too?

Yes sure, giving an update asap

2024-12-24 07:03 UTC, 0xriyadh commented
@riya09 should we have votings in `jobab comments` as well?

2024-12-25 03:48 UTC, 0xriyadh commented
@riya09 done with with all the major endpoints I could think of. Please let me know if I have missed anything.

2024-12-25 17:57 UTC, riya09 requested changes

2024-12-25 17:57 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +    });
make a function in this file,
```js
const COMMENTS_PER_PAGE = 8;
const REPLIES_PER_PAGE = 4;



async function processCommentUrls(comments: any[], ctx: any) {
    return Promise.all(comments.map(async comment => ({
        ...comment,
        profile_picture: comment.profile_picture
            ? await ctx.services.fileStorage.getFileURL(comment.profile_picture)
            : null,
        total_votes: Number(comment.total_votes)
    })));
}

const withVotes = (qb: any, userId?: string) => {
    qb.leftJoin(
        'jobab_comment_votes',
        'jobab_comments.id',
        'jobab_comment_votes.comment_id'
    );
    
    if (userId) {
        qb.leftJoin('jobab_comment_votes as user_vote', join =>
            join.onRef('jobab_comments.id', '=', 'user_vote.comment_id')
                .on('user_vote.user_id', '=', userId)
        );
    }
    
    return qb;
};
```

then use here like this
```js
export const listPublicComments = publicProcedure
    .input(z.object({
        jobab_id: z.number(),
        page: z.number()
    }))
    .query(async ({ input, ctx }) => {
        const comments = await withVotes(baseCommentQuery(ctx.services.postgresQueryBuilder, input.jobab_id))
            .select(getCommentFields())
            .groupBy(['users.id', 'jobab_comments.id'])
            .where('jobab_comments.parent_id', 'is', null)
            .orderBy('total_votes', 'desc')
            .orderBy('jobab_comments.created_at', 'asc')
            .limit(COMMENTS_PER_PAGE)
            .offset((input.page - 1) * COMMENTS_PER_PAGE)
            .execute();

        return {
            data: await processCommentUrls(comments, ctx)
        };
    });
```

2024-12-25 17:57 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +            .where('jobab_comments.deleted_at', 'is', null)
since this same query has been used in most of the function, we can make a helper function
```js
const baseCommentQuery = (qb: any, jobabId: number) => 
    qb.selectFrom('jobab_comments')
        .innerJoin('users', 'jobab_comments.created_by', 'users.id')
        .where('jobab_comments.jobab_id', '=', jobabId)
        .where('jobab_comments.deleted_at', 'is', null);
```
then use it like this
```js
export const countAllComments = publicProcedure
    .input(z.object({ jobab_id: z.number() }))
    .query(async ({ input, ctx }) => {
        const result = await baseCommentQuery(ctx.services.postgresQueryBuilder, input.jobab_id)
            .select(eb => eb.fn.count('jobab_comments.id').as('count'))
            .executeTakeFirst();

        return { data: { count: Number(result?.count ?? 0) } };
    });
```

2024-12-25 17:57 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +export const listReplies = publicProcedure
check if you can use helper functions in rest of the endpoints, may help to reduce redundancy

2024-12-27 03:28 UTC, 0xriyadh commented
@riya09 can you please check if I understood everything correctly and if further changes are needed.

2024-12-27 17:47 UTC, riya09 requested changes

2024-12-27 17:47 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +export const countComments = publicProcedure
I would suggest rename to `countRootComments` to make it more readable

2024-12-27 17:47 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +export const listPublicReplies = publicProcedure
I think you can combine `listPublicReplies` and `listReplies`. 
```js
export const getReplies = publicProcedure
    .input(z.object({
        jobab_id: z.number(),
        parent_id: z.number(),
        page: z.number(),
    }))
    .query(async ({input, ctx}) => {
        const hasUser = !!ctx.auth?.user_id;
        const replies = await withVotes(
            baseCommentQuery(ctx.services.postgresQueryBuilder, input.jobab_id),
            hasUser ? `${ctx.auth.user_id}` : undefined
        )
            .select([
                ...getCommentFields(),
                ...(hasUser ? ['user_vote.vote as user_vote'] : [])
            ])
            .groupBy([
                ...(hasUser ? ['user_vote.vote'] : []),
                'users.id', 
                'jobab_comments.id'
            ])
            .where('jobab_comments.parent_id', '=', input.parent_id)
            .orderBy('jobab_comments.created_at', 'asc')
            .limit(REPLIES_PER_PAGE)
            .offset((input.page - 1) * REPLIES_PER_PAGE)
            .execute();

        return {
            data: await processCommentUrls(replies, ctx),
        };
    });
    ```

2024-12-27 18:00 UTC, 0xriyadh commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +export const countComments = publicProcedure
I followed the naming convention from here `apps/jonogon-core/src/api/trpc/procedures/comments/crud.mts`. Should we change both of them?

2024-12-27 18:01 UTC, 0xriyadh commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +export const listPublicReplies = publicProcedure
followed this from `apps/jonogon-core/src/api/trpc/procedures/comments/crud.mts` as should we change both of them?

2024-12-27 18:15 UTC, 0xriyadh commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +        const comment = await ctx.services.postgresQueryBuilder
Can you please explain a bit here? The `baseCommentQuery` takes `jobabId` as input, but we do not need `jobabId` to update or delete a comment. Would love to hear your thought.

2024-12-27 18:52 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +export const listPublicReplies = publicProcedure
I think just change here first only

2024-12-27 18:52 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +export const countComments = publicProcedure
not in this PR

2024-12-27 19:12 UTC, riya09 commented on apps/jonogon-core/src/api/trpc/procedures/jobabs/comments.mts
> +        const comment = await ctx.services.postgresQueryBuilder
yeah, not possible to use helper function. Sorry, my bad

2024-12-28 16:32 UTC, 0xriyadh commented
@riya09 all done

2025-01-02 16:13 UTC, merged